/* DEC/CMS REPLACEMENT HISTORY, Element GRID_FILES.SQL */
/* *4    14-JUN-1991 13:03:03 ERIC "(SPR 1) Reformatted" */
/* *3    24-MAY-1990 21:00:42 DOROTHY "(SPR 5182) UPDATED PER CHANGES TO DATABASE TABLES." */
/* *2    29-SEP-1989 12:12:20 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 10:59:00 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element GRID_FILES.SQL */
SET LONG 1024;
SET PAGESIZE 55;
SET LINESIZE 80;
SET SPACE 1
SET VERIFY OFF;
SET NEWPAGE 0;

TTITLE CENTER 'GRIDDED DATA FILES REFERENCED BY &1 MAP DEFINITIONS' -
       SKIP 2 -
       CENTER ' Sorted by Map Name' -
       SKIP 4;

COLUMN MAP_NAME FORMAT A31 HEADING 'MAP NAME';
COLUMN KEYWORD FORMAT A18;
COLUMN PARAMETER FORMAT A29 HEADING 'GRID FILE NAME';

SELECT MAP_NAME, KEYWORD, PARAMETER
       FROM &1..MAP_OVERLAYS
       WHERE KEYWORD = 'GRID FILE: INPUT'
	OR KEYWORD = 'GRID FILE: OUTPUT'
       ORDER BY MAP_NAME
/
