C  DEC/CMS REPLACEMENT HISTORY, Element SYN_PLT_DRV.FOR
C  *1    10-AUG-1989 18:52:23 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element SYN_PLT_DRV.FOR
      SUBROUTINE SYN_PLOT_DRIVER( PARMFILE )
C
C 01/05/89 GS - Behave like other plot rtns -- get parmfile from argument,
C 		not stdin

      CHARACTER*(*) PARMFILE
      CHARACTER*240 DATAFILE
      CHARACTER*40  COMMEN
      CHARACTER*1   DISP
      CALL HOGFNT(IUNIT)
C      READ(5,1)PARMFILE
      OPEN(IUNIT,FILE=PARMFILE,FORM='FORMATTED',STATUS='OLD')
      READ(IUNIT,1)DATAFILE
1     FORMAT(A)
      READ(IUNIT,1)COMMEN
      READ(IUNIT,2)SCALE
2     FORMAT(F15.5)
      READ(IUNIT,2)PLTSPD
      READ(IUNIT,3)NTRCES
3     FORMAT(I10)
      READ(IUNIT,2)TRSP
      READ(IUNIT,1)DISP
      READ(IUNIT,3)IRESLOG
      READ(IUNIT,3)IFEET
      CLOSE(IUNIT,STATUS='DELETE')
      IFBATCH = 1
      CALL SYNPLOTTER(DATAFILE,COMMEN,SCALE,PLTSPD,NTRCES,TRSP,
     X   DISP,IRESLOG,IFEET,IFBATCH)
      RETURN
      END

