C  DEC/CMS REPLACEMENT HISTORY, Element TF_AGC.FOR
C  *2    19-SEP-1989 10:18:32 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:53:26 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_AGC.FOR
C
C ****************************************************************************
C
      SUBROUTINE AGC(N,A,NGATE)
C MODIFIED BY J. GILLESPIE 2 OCT 86
C CALCULATE ARRAY OF SQUARES, AND PERFORM RUNNING AVERAGE INSTEAD OF
C CALCULATING NEW RMS VALUE FOR EVERY GATE POSITION
C
C
C   N  NUMBER OF INPUT POINTS
C   A  INPUT VECTOR
C   NGATE  GATE LENGTH FOR SCALING COMPUTATION
C
      PARAMETER (ICOMMONSIZE = 32768)
      DIMENSION A(1), AOUT(ICOMMONSIZE)
      COMMON/HNGLIBCOM/AOUT
C
C COMPUTE TRACE RMS
C
      IF(N.LE.NGATE)RETURN
      DO 10 JK = 1, N
10    AOUT(JK) = A(JK)
C
      CALL RMSARRAY(N,AOUT,RMSS)
      ISTRT=NGATE/2
C
      DO 100 I=1,N-NGATE+1
C
C STUFF INTO TEMP BUFFER FOR GATE AGC COMPUTATION
C
C
C COMPUTE RMS WITHIN RMS GATE LENGTH
C
      IF (I .EQ. 1) THEN
            SUM =0.0
            DO 20 JK = 1, NGATE
20          SUM = SUM + AOUT(JK)
      ELSE
            SUM = SUM - AOUT(I - 1) + AOUT(I + NGATE - 1)
      ENDIF
      IF(SUM.GE.0.0)THEN
          RMSG = SQRT(SUM / FLOAT(NGATE))
      ELSE
          RMSG=0.0
      ENDIF
C
C COMPUTE AND APPLY SCALER
C
      IF(RMSG.EQ.0.0)THEN
          SCALE=0.0
      ELSE
         SCALE=RMSS/RMSG
      ENDIF
C
C APPLY CONSTANT SCALER TO FRONT END DATA
C
      IF(I.EQ.1) THEN
          DO 3 L=1,ISTRT
3         A(L)=A(L)*SCALE
      ELSE
          A(ISTRT)=A(ISTRT)*SCALE
      ENDIF
      ISTRT=ISTRT+1
100   CONTINUE
C
C APPLY FINAL SCALER TO END OF DATA
C
      DO 5 I=ISTRT,N
5     A(I)=A(I)*SCALE
C
C
      RETURN
      END
