C  DEC/CMS REPLACEMENT HISTORY, Element TF_BINEXP.FOR
C  *2    19-SEP-1989 10:18:42 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:53:32 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_BINEXP.FOR
C
C ****************************************************************************
C
      SUBROUTINE BINEXP(NN,NBIN)
C
C THIS SUBROUTINES THE RETURNS A BINARY EXPONENT FOR A NUMBER.  IF THE
C NUMBER IS NOT AN EVEN POWER OF 2, THE EXPONENT IS RETURNED AS THAT OF
C OF THE NEXT HIGHEST EVEN POWER OF 2.
C
C NN = NUMBER OF BE EVALUATED
C NBIN = RETURNED BINARY EXPONENT
C
      NBIN=0
      IF(NN.LE.0)RETURN
      NBIN = ALOG10(FLOAT(NN)) / ALOG10(2.0) + .001
      IF(2**NBIN.LT.NN)NBIN=NBIN+1
      RETURN
      END
