C  DEC/CMS REPLACEMENT HISTORY, Element TF_CORR.FOR
C  *2    19-SEP-1989 10:18:52 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:53:42 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_CORR.FOR
C
C ****************************************************************************
C
      SUBROUTINE CORR(A,B,C,KK,J,L)
C
C IF YOU ARE GOING TO CONVOLVE, FLIPED ARRAY IS A
C
C THIS SUBROUTINE PERFORMS A CROSS, MULTIPLY, SUM CORRELATION BETWEEN TWO
C ARRAYS AND RETURNS THE CORRELATION ARRAY.
C
C A   = FIRST ARRAY TO CORRELATE, WHOLE ARRAY USED, SMALL ARRAY
C B   = SECOND ARRAY TO CORRELATE, KK ELEMENTS USED, LARGER ARRAY
C C   = CORRELATION ARRAY
C KK  = NUMBER OF POINTS IN A ARRAY
C J   = NUMBER OF POINTS IN B ARRAY
C L   = NUMBER OF POINTS RETURNED IN C ARRAY
C
      DIMENSION A(1),B(1),C(1)
      REAL*8 SUM,ADDED,BADDED
      DO 44 LO=1,J
      SUM=0.
      K=LO
      DO 45 LM=1,KK
      IF(K.GT.J)GOTO 100
      IF(A(LM) .GT. -1.0E-35 .AND. A(LM) .LT. 1.0E-35)A(LM)=0.0
      IF(B(K) .GT. -1.0E-35 .AND. B(K) .LT. 1.0E-35)B(K)=0.0
      ADDED=A(LM)
      BADDED=B(K)
      ADDED = ADDED * BADDED
      SUM=SUM+ADDED
   45 K=K+1
100   IF(SUM .GT. -1.0E-35 .AND. SUM .LT. 1.0E-35)SUM=0.0
      C(LO)=SUM
   44 CONTINUE
      L=J
      RETURN
      END
