C  DEC/CMS REPLACEMENT HISTORY, Element TF_LAG.FOR
C  *2    19-SEP-1989 10:19:26 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:54:04 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_LAG.FOR
C
C ****************************************************************************
C
      SUBROUTINE LAG(A,IA,AOUT,IAA)
C
C DO A LA GRANGE METHOD RESAMPLING OF AN ARRAY, 9TH ORDER
C
C A    = IN ARRAY TO BE RESAMPLED
C IA   = NUMBER OF POINTS IN A
C AOUT = OUTPUT ARRAY, RESAMPLED INPUT ARRAY A
C IAA  = NUMBER OF POINTS WANTED OUT IN AOUT
C
      DIMENSION A(1),AOUT(1)
C
C FO IS A CONSTANT FOR BEGINNING EDGE
C
      FO=A(1)
C
C  NEW NUMBER OF POINTS
C
C X INCREMENT OF NEW ARRAY
C
      IF(IAA.EQ.1) THEN
         AOUT(1)=A(1)
         RETURN
      ENDIF
      XINC = (IA-1.0)/(IAA-1.0)
C
C BEGINNING X
C
      XX = 0
C
C ORDER OF FIT
C
      IORD=9
C
C LOOP THROUGH FOR EACH NEW POINT
C
      AOUT(1)=A(1)
      DO 100 JK = 2,IAA-1
C
C INCREMENT X
C
         XX = XX + XINC
         CALL LLLL(IA,IORD,XX,A,SUM,FO)
         AOUT(JK) = SUM
100   CONTINUE
C
C SET LAST TO LAST
C
       AOUT(IAA) = A(IA)
       RETURN
       END
C
C ****************************************************************************
C
      SUBROUTINE LLLL(NPTS,NORD,XX,Y,SUM,FO)
C
C RETURNS VALUE TO LAG FOR RESAMPLING
C
C NPTS = NUMBER OF POINTS IN INPUT ARRAY
C NORD = ORDER OF FIT
C XX   = X POSITION OF NEW FIT
C Y    = INPUT ARRAY
C SUM  = RETURNED Y VALUE FOR POINT XX
C FO   = FRONT END CONSTANT
      DIMENSION Y(1),XSAVE(50),YSAVE(50),ANSL(50)
C
C FIND INDEX IF XX POSITION
      I = XX+1
C
      IODD = (-1) ** NORD
    6 IF(IODD.EQ.-1) II=I-(NORD/2+1)
      IF(IODD.EQ.1) II=I-(NORD/2)
C
C  COMPUTE RANGE OF LOOP FOR INTEROP.
C
      IJ=II+NORD-1
      K=1
C
C  STUFF INTO XSAVE AND YSAVE
C
      DO 10 III=II,IJ
         XSAVE(K)=III
         YSAVE(K) = FO
         VALUE=Y(NPTS)
         IF(III.LT.NPTS-1.AND.III.GE.0)VALUE=Y(III+1)
         IF(III.GE.0)YSAVE(K)=VALUE
         K=K+1
   10 CONTINUE
      K=K-1
C
C  COMPUTE THE INTERPOLATED Y VALUE FOR INTERP X
C
      DO 100 I=1,NORD
         ANSNUM=1.
         ANSDEN=1.
         DO 101 J=1,K
            IF(I.EQ.J) GOTO 101
            IF(XSAVE(I).EQ.XSAVE(J))GOTO 101
            ANSNUM=ANSNUM*(XX-XSAVE(J))
            ANSDEN=ANSDEN*(XSAVE(I)-XSAVE(J))
  101    CONTINUE
         ANSL(I)=ANSNUM/ANSDEN
  100 CONTINUE
C
      SUM=0.
C
C SUM IT
C
      DO 102 I=1,K
         SUM=SUM+YSAVE(I)*ANSL(I)
  102 CONTINUE
C
C  SUM IS THE ANSWER
C
      RETURN
      END
