C  DEC/CMS REPLACEMENT HISTORY, Element TF_MINMAX.FOR
C  *2    19-SEP-1989 10:19:35 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:54:08 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_MINMAX.FOR
C
C ****************************************************************************
C
      SUBROUTINE MINMAX(NPTS,VALUE,XMIN,XMAX)
C
C THIS SUBROUTINE CALCULATES THE MINIMUM AND MAXIMUM VALUES OF A REAL*4 ARRAY.
C NPTS  = NUMBER OF POINTS IN ARRAY
C VALUE = ARRAY OF FLOATING POINT VALUES TO BE EXAMINED
C XMIN  = MINIMUM VALUE FOUND IN ARRAY
C XMAX  = MAXIMUM VALUE FOUND IN ARRAY
C
      DIMENSION VALUE(1)
      XMIN=VALUE(1)
      XMAX=VALUE(1)
      DO 100 I=1,NPTS
      IF(XMIN.GT.VALUE(I)) XMIN=VALUE(I)
      IF(XMAX.LE.VALUE(I)) XMAX=VALUE(I)
  100 CONTINUE
      RETURN
      END
