C  DEC/CMS REPLACEMENT HISTORY, Element TF_RMSARRAY.FOR
C  *2    19-SEP-1989 10:19:44 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:54:12 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element TF_RMSARRAY.FOR
C
C ****************************************************************************
C
      SUBROUTINE RMSARRAY(N,VALUE,RMSS)
C
C THIS SUBROUTINE CALCULATES THE RMS VALUE OF AN ARRAY OF FLOATING PT.
C NUMBERS AND RETURNS THE ARRAY OF SQUARES.
C
C N     = NUMBER OF POINTS IN ARRAY
C VALUE = ARRAY TO BE EXAMINED AND SQUARES ARE RETURNED IN IT
C RMSS  = ROOT MEAN SQAURE VALUE CALCULATED FROM ARRAY
C
      DIMENSION VALUE(1)
      REAL*8 TSQ,PRODUCT
      TSQ=0.
      IA=0.
C
C SUM SQUARES
C
      DO 100 IS=1,N
         IF(VALUE(IS).EQ.0.) GO TO 100
         PRODUCT = VALUE(IS)*VALUE(IS)
         IF(PRODUCT.GT.-1.0E-37.AND.PRODUCT.LT.1.0E-37)PRODUCT=0.0
         VALUE(IS)=PRODUCT
         TSQ=TSQ+PRODUCT
         IA=IA+1
  100 CONTINUE
      IF(IA.EQ.0) RMSS=0.
      IF(IA.EQ.0) RETURN
C
C TAKE SQUARE ROOT OF MEAN
C
      TSQ=SQRT(TSQ/FLOAT(IA))
      IF(TSQ.GT.-1.0E-37.AND.TSQ.LT.1.0E-37)TSQ=0.0
      RMSS=TSQ
      RETURN
      END
