ag "Analytic Geometry"
am "Application Manager"
as "Application Server"
bt "BTree Functions"
ci "Command Interpreter"
co "Contour Overlay"
cp "Data Mover"
cs "Centered Symbols"
ct "Cartographic Transformations"
db "Database"
dd "Data Digitizing"
dg "Dynamic Graphics"
dr "Data Rendering"
ee "Expression Evaluation"
er "Error Reporting"
fi "Finder Core"
fm "File Manager"
gb "Global Select Lists"
gd "Grid Display"
ge "Grid Display"
gf "Glue Functions"
go "Graphic Object"
gq "Geoquest Interface"
gr "Graticule"
hf "Help Functions"
hl "Highlighting"
ho "Host Dependent"
ht "Hash Table Functions"
jg "Jeffersonian Land Grid"
ld "Loader"
le "Line Editor"
lg "Log Trace"
lh "List Head Functions"
ll "Linked Lists"
lm "Lease Management"
ls "Leases"
lu "Lookup Functions"
ly "Lynx Functions"
md "Map Definition"
mg "Message Strings"
mk "Map Section Labels"
mm "Mapping Functions"
mo "Mapping Overlay"
mp "Map Plotting"
mr "Map Registration"
nf "Plotting"
ni "Neutral Interface Plotting"
nl "NLIST Functions"
np "Neutral Device Plotting"
or "Oracle Tools"
ov "Overlay Functions"
pd "Plotting Interface"
pf "Plotting Tools"
pl "Plotting Library"
pr "Projections"
ps "Pointer Stack"
qs "Query - Set Functions"
rs "Resource Compiler"
rt "Raster Tech Functions"
s3 "3D Seismic Functions"
sd "Seismic Display"
se "Seismic Lines"
sf "Seismic Filter Functions"
sl "Select Lists"
so "Seismic Overlay"
ss "Seismic Survey"
sx "Shot Labels"
sy "Synthetic Waveforms"
tc "Tools"
tf "Fortran Tools "
tg "Tablet Graphic Transforms"
tm "Test tools "
to "Tools for Overlays"
ts "String Tools"
tu "Tools for Unit of Measures"
ug "GKS tools"
ui "User Interface Toolkit"
uk "Ukooa Loader Functions"
ut "Utility Toolbox"
v3"
v4"
vi Velocity Interface"
we Wells"
wi Workstation Interface"
wl Well Functions"
wm Window Manager"
xd Cross Section Display"
xf XWindow Finder Library"
xs Cross Secion Application"
