/* DEC/CMS REPLACEMENT HISTORY, Element ORA_FORMS.SQL */
/* *2    29-SEP-1989 12:36:00 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:15:16 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element ORA_FORMS.SQL */

DOC
	ESI ORACLE FORMS REPORT
	p1 = Project Name
#

COLUMN NAME FORMAT A30 HEADING Name
COLUMN TYPE HEADING 'Data|Type' FORMAT A7
COLUMN DESCRIPTION FORMAT A75  HEADING Description
COLUMN SCOPE FORMAT A7 HEADING Scope

TTITLE 	CENTER ' -->  --> &1 ORACLE Forms <--  <-- '

SELECT NAME, 'PROJECT' SCOPE, TYPE, DESCRIPTION
FROM 	&1..ORACLE_FORMS
UNION
SELECT NAME, 'SYSTEM' SCOPE, TYPE, DESCRIPTION
FROM	ESI.ORACLE_FORMS
ORDER BY 1;
