/* DEC/CMS REPLACEMENT HISTORY, Element ORA_SCRIPTS.SQL */
/* *2    29-SEP-1989 12:36:27 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:17:12 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element ORA_SCRIPTS.SQL */
DOC
	ESI Well Header Report
	p1 = Project Name
	p2 = name of control list table
        p3 = name of original select list
#
SET NEWPAGE 0
SET LINESIZE 132
SET PAGES 55


BREAK ON DATA_TYPE SKIP 2

COLUMN NAME FORMAT A30 HEADING 'Script Name'
COLUMN DATA_TYPE HEADING 'Data|Type' FORMAT A7
COLUMN SCRIPT_TYPE HEADING 'Script|Type' FORMAT A10
COLUMN CONTROL_LIST_REQUIRED HEADING 'Ctrl|Reqd' FORMAT A4
COLUMN DESCRIPTION FORMAT A65 HEADING Description
COLUMN SCOPE FORMAT A7 HEADING 'Scope'

TTITLE 	CENTER ' -->  --> &1 ORACLE Scripts <--  <-- '

SELECT 'PROJECT' SCOPE, NAME, DATA_TYPE, SCRIPT_TYPE,
	CONTROL_LIST_REQUIRED, DESCRIPTION
FROM 	&1..ORACLE_SCRIPTS
UNION
SELECT 'SYSTEM' SCOPE, NAME, DATA_TYPE, SCRIPT_TYPE,
	CONTROL_LIST_REQUIRED, DESCRIPTION
FROM	ESI.ORACLE_SCRIPTS
ORDER BY 3;
