/* DEC/CMS REPLACEMENT HISTORY, Element ORACLE_FORMS.SQL */
/* *3    14-JUN-1991 13:12:34 ERIC "(SPR 1) Reformatted" */
/* *2     8-JUN-1991 16:41:07 ERIC "(SPR 1) Fixed formatting problems." */
/* *1    19-JUN-1989 14:53:39 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element ORACLE_FORMS.SQL */
DOC
	ESI ORACLE FORMS REPORT
	p1 = Project Name
#
SET SPACE 2
SET LINESIZE 80

COLUMN NAME FORMAT A25
COLUMN TYPE HEADING 'Data|Type' FORMAT A7
COLUMN DESCRIPTION FORMAT A35
COLUMN SCOPE FORMAT A7

TTITLE 	CENTER ' -->  --> &1 ORACLE Forms <--  <-- '

SELECT NAME, 'PROJECT' SCOPE, TYPE, DESCRIPTION
FROM 	&1..ORACLE_FORMS
UNION
SELECT NAME, 'SYSTEM' SCOPE, TYPE, DESCRIPTION
FROM	ESI.ORACLE_FORMS
ORDER BY 1;
