/* DEC/CMS REPLACEMENT HISTORY, Element ORACLE_SCRIPTS.SQL */
/* *1    19-JUN-1989 14:53:42 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element ORACLE_SCRIPTS.SQL */
DOC
	ESI Well Header Report
	p1 = Project Name
	p2 = name of control list table
        p3 = name of original select list
#

COLUMN NAME FORMAT A30
COLUMN DATA_TYPE HEADING 'Data|Type' FORMAT A7
COLUMN SCRIPT_TYPE HEADING 'Script|Type' FORMAT A10
COLUMN CONTROL_LIST_REQUIRED HEADING 'CTRL' FORMAT A4
COLUMN DESCRIPTION FORMAT A65
COLUMN SCOPE FORMAT A7

TTITLE 	CENTER ' -->  --> &1 ORACLE Scripts <--  <-- '

SELECT 'PROJECT' SCOPE, NAME, DATA_TYPE, SCRIPT_TYPE,
	CONTROL_LIST_REQUIRED, DESCRIPTION
FROM 	&1..ORACLE_SCRIPTS
UNION
SELECT 'SYSTEM' SCOPE, NAME, DATA_TYPE, SCRIPT_TYPE,
	CONTROL_LIST_REQUIRED, DESCRIPTION
FROM	ESI.ORACLE_SCRIPTS
ORDER BY 2;
