C  DEC/CMS REPLACEMENT HISTORY, Element MO_EMP_DRV.FOR
C  *3     3-NOV-1989 12:01:19 GILLESPIE "(SPR 30) Change entry points for new n-List nomenclature"
C  *2    19-SEP-1989 10:12:45 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:48:16 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element MO_EMP_DRV.FOR
      INTEGER*4 FUNCTION MO_EMP_DRIVER(PL_PTR,PLV_PTR,MO_PTR,
     X   ICOMMAND)
C
      INCLUDE 'mo_struct.i'
      INCLUDE 'mo_strat.ri'
C
C PL_PTR = POINTER OF N-LIST
C PLV_PTR = POINTER OF VELOCITY N-LIST
C MO_PTR = ROW OF MO_STRUCT
C
      REAL*8 PL_PTR,MO_PTR,PLV_PTR
      INTEGER*4 ICOMMAND,STATUS,NRMAX
      CHARACTER*128 PLOT_FILE,NAME*130,EMP_FILE
      SAVE PLOT_FILE,NAME,EMP_FILE,NRMAX
      DATA PLOT_FILE/' '/,EMP_FILE/' '/
C
C
C MAKE SONICS
C
      IF(ICOMMAND.EQ.GENERATE_MODEL)THEN
       IF(EMP_FILE.NE.' ')THEN
           CALL DELFIL(EMP_FILE,IERR)
           EMP_FILE=' '
       ENDIF
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE = ' '
       ENDIF
       CALL MO_EMP_SONICS(PLV_PTR,PL_PTR,MO_PTR,NAME,EMP_FILE,STATUS)
       MO_EMP_DRIVER = STATUS
       RETURN
      ENDIF
C
C PLOT RESULT
C
      IF(ICOMMAND.EQ.MO_DRAW_TIEPLOT)THEN
       CALL MO_TIEPLOT('EMP',EMP_FILE,NAME,STATUS)
       MO_EMP_DRIVER = STATUS
       RETURN
      ENDIF
C
C CALCULATE TRACES
C
      IF(ICOMMAND.EQ.GENERATE_TRACES)THEN
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE=' '
       ENDIF
      NRMAX = 0
       CALL MO_TIE_TRACES('EMP',EMP_FILE,NAME,PLOT_FILE,NRMAX,STATUS)
       MO_EMP_DRIVER = STATUS
       RETURN
      ENDIF
C
C PLOT TRACES
C
      IF(ICOMMAND.EQ.MO_TRACES)THEN
       CALL MO_PLOT(PLOT_FILE,NAME,NRMAX)
       MO_EMP_DRIVER = 0
       RETURN
      ENDIF
C
C SHUTDOWN
C
      IF(ICOMMAND.EQ.MO_F77_SHUTDOWN)THEN
       IF(EMP_FILE.NE.' ')THEN
           CALL DELFIL(EMP_FILE,IERR)
           EMP_FILE=' '
       ENDIF
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE=' '
       ENDIF
       MO_EMP_DRIVER = 0
       RETURN
      ENDIF
C
C UNKNOWN COMMAND
C
      MO_EMP_DRIVER = 1
      RETURN
      END
C END-CODE
