C  DEC/CMS REPLACEMENT HISTORY, Element MO_TIE_DRV.FOR
C  *3     3-NOV-1989 12:02:40 GILLESPIE "(SPR 30) Change entry points for new n-List nomenclature"
C  *2    19-SEP-1989 10:14:50 GORDON "(PURNA) GULF MODS UNDER SPR 100"
C  *1    10-AUG-1989 18:49:47 VINCE "Fortran code after UNIX mods"
C  DEC/CMS REPLACEMENT HISTORY, Element MO_TIE_DRV.FOR
      INTEGER*4 FUNCTION MO_TIE_DRIVER(PL_PTR,MO_PTR,ICOMMAND)
C
      INCLUDE 'mo_strat.ri'
      INCLUDE 'mo_struct.i'
C
C PL_PTR = POINTER OF N-LIST
C MO_PTR = ROW OF MO_STRUCT
C
      REAL*8 PL_PTR,MO_PTR
      INTEGER*4 ICOMMAND,STATUS,NRMAX
      CHARACTER*128 PLOT_FILE,NAME*130,TIE_FILE
      SAVE PLOT_FILE,NAME,TIE_FILE,NRMAX
      DATA PLOT_FILE/' '/,TIE_FILE/' '/
C
C
C MAKE SONICS
C
      IF(ICOMMAND.EQ.GENERATE_MODEL)THEN
       IF(TIE_FILE.NE.' ')THEN
           CALL DELFIL(TIE_FILE,IERR)
           TIE_FILE=' '
       ENDIF
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE = ' '
       ENDIF
       CALL MO_TIE_SONICS(PL_PTR,MO_PTR,NAME,TIE_FILE,STATUS)
       MO_TIE_DRIVER = STATUS
       RETURN
      ENDIF
C
C PLOT RESULT
C
      IF(ICOMMAND.EQ.MO_DRAW_TIEPLOT)THEN
       CALL MO_TIEPLOT('TIE',TIE_FILE,NAME,STATUS)
       MO_TIE_DRIVER = STATUS
       RETURN
      ENDIF
C
C CALCULATE TRACES
C
      IF(ICOMMAND.EQ.GENERATE_TRACES)THEN
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE=' '
       ENDIF
       NRMAX=0
       CALL MO_TIE_TRACES('TIE',TIE_FILE,NAME,PLOT_FILE,NRMAX,STATUS)
       MO_TIE_DRIVER = STATUS
       RETURN
      ENDIF
C
C PLOT TRACES
C
      IF(ICOMMAND.EQ.MO_TRACES)THEN
       CALL MO_PLOT(PLOT_FILE,NAME,NRMAX)
       MO_TIE_DRIVER = 0
       RETURN
      ENDIF
C
C SHUTDOWN
C
      IF(ICOMMAND.EQ.MO_F77_SHUTDOWN)THEN
       IF(TIE_FILE.NE.' ')THEN
           CALL DELFIL(TIE_FILE,IERR)
           TIE_FILE=' '
       ENDIF
       IF(PLOT_FILE.NE.' ')THEN
           CALL DELFIL(PLOT_FILE,IERR)
           PLOT_FILE=' '
       ENDIF
       MO_TIE_DRIVER = 0
       RETURN
      ENDIF
C
C UNKNOWN COMMAND
C
      MO_TIE_DRIVER = 1
      RETURN
      END
C END-CODE
