/* DEC/CMS REPLACEMENT HISTORY, Element CONTOUR_FILES.SQL */
/* *4    14-JUN-1991 12:38:17 ERIC "(SPR 1) Fixed format problem." */
/* *3    24-MAY-1990 20:23:18 DOROTHY "(SPR 5182) UPDATED REPORT PER CHANGES TO DATABASE TABLE." */
/* *2    29-SEP-1989 12:04:36 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 10:58:21 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element CONTOUR_FILES.SQL */
SET LONG 1024;
SET PAGESIZE 55;
SET LINESIZE 132;
SET SPACE 4
SET VERIFY OFF;
SET NEWPAGE 0;

TTITLE CENTER 'CONTOUR FILES REFERENCED BY &1 MAP DEFINITIONS' -
       SKIP 2 -
       CENTER ' Sorted by Map Name' -
       SKIP 4;

COLUMN MAP_NAME FORMAT A40 HEADING 'MAP NAME';
COLUMN KEYWORD FORMAT A21 HEADING 'Keyword';
COLUMN PARAMETER FORMAT A60 HEADING 'CONTOUR FILE NAME';

SELECT MAP_NAME, KEYWORD, PARAMETER
       FROM &1..MAP_OVERLAYS
       WHERE KEYWORD = 'CONTOUR FILE: OUTPUT'
	OR KEYWORD = 'CONTOUR FILE: INPUT'
       ORDER BY MAP_NAME
/
