/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY.SQL */
/* *4    20-AUG-1991 17:04:37 ERIC "(SPR 1) Removed select list functionality." */
/* *3    16-JUL-1990 18:39:51 ALLAWAY "(SPR -1) CHECKIN FOR 7-15-90 SCHEMA UPDATE" */
/* *2    26-MAR-1990 11:39:17 DOROTHY "(SPR -1) Schema fix." */
/* *1    19-JUN-1989 14:53:45 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY.SQL */
DOC
	ESI Well Checkshot Survey Report
	p1 = Project Name
	p2 = name of control list table
        p3 = name of original select list
#

CLEAR 	BREAKS;

BREAK ON WELLNAME SKIP 1 -
ON UWI NODUP

SET NEWPAGE 0
SET PAGESIZE 55
SET LINESIZE 100
SET SPACE 3

COLUMN MD FORMAT 99,999.9 HEADING 'Measured|Depth'
COLUMN TIME FORMAT 9999.9 HEADING 'Time'
COLUMN UWI FORMAT A17 HEADING 'UWI'
COLUMN WELLNAME FORMAT A30 HEADING 'Well Name'
COLUMN SOURCE FORMAT A14 HEADING 'Source'
COLUMN TIME_UNIT FORMAT A8 HEADING 'Time|Unit'

TTITLE 	' -->  --> Project &1 Well Checkshot Survey Report <--  <-- '

SELECT  
	A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME, 
	A.UWI,
	SOURCE,
	MD, 
	TIME,
	TIME_UNIT
FROM 	
	&1..WELL_HDR A, 
	&1..WELL_CHECKSHT_SRVY B
WHERE	
	A.UWI = B.UWI 
ORDER BY 
	A.WELL_NAME, 
	A.WELL_NUMBER, 
	MD;
