/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS.SQL */
/* *3    26-MAR-1990 11:42:17 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:56:30 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:43:12 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS.SQL */
CLEAR 	BREAKS;
BREAK	ON WELLNAME ON OPERATOR ON UWI  SKIP 2;

SET NEWPAGE 0
SET LINESIZE 132
SET PAGES 55
SET SPACE 3

COLUMN OPERATOR FORMAT A20 HEADING 'Operator';
COLUMN SOURCE FORMAT A10 HEADING 'Source';
COLUMN MD FORMAT 99,999.9 HEADING 'Meas.|Depth'
COLUMN FORM_CODE HEADING 'Formation' FORMAT A12
COLUMN WELLNAME HEADING 'Well Name' FORMAT A12
COLUMN LAST_UPDATE HEADING 'Last|Update'
COLUMN UWI HEADING 'Unique Identifier' FORMAT A20

TTITLE 	CENTER 	'&1 Tops Report' SKIP CENTER 'Sorted by Well Name';

SELECT  
  A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME,
  A.UWI,   
  A.OPERATOR,
  D.FORM_CODE, 
  D.MD, 
  D.SOURCE, 
  D.LAST_UPDATE
FROM 	
  &1..WELL_TOPS D, 
  &1..WELL_HDR A
WHERE	
  A.UWI = D.UWI 
ORDER BY A.WELL_NAME, A.WELL_NUMBER, D.MD, D.SOURCE;
