/* DEC/CMS REPLACEMENT HISTORY, Element WELL_STATUS_CODES.SQL */
/* *3    26-MAR-1990 11:41:28 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:54:14 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:40:39 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_STATUS_CODES.SQL */
SET NEWPAGE 0
SET PAGESIZE 55
SET LINESIZE 80
SET SPACE 4

TTITLE '>------ FINDER Well Status Codes ------<'
COL REMARKS FORMAT A40 HEADING 'Description'
COL STATUS FORMAT A30 HEADING 'Status Code'

SELECT
   STATUS,
   REMARKS
FROM 
   CODES.WELL_STATUS_CODES
ORDER BY STATUS
/
