/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_OPERATOR.SQL */
/* *4    14-JUN-1991 13:16:46 ERIC "(SPR 1) Reformatted" */
/* *3    26-MAR-1990 11:40:48 DOROTHY "(SPR -1) Schema fix." */
/* *2    26-JAN-1990 14:43:34 MING "(SPR 0) change A.UWI = B.NODE_ID to A.NODE_ID = B.NODE_ID for unique node_id" */
/* *1    19-JUN-1989 14:53:50 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_OPERATOR.SQL */
DOC
	ESI Well Header Report
	p1 = Project Name
	p2 = name of control list table
#

SET NEWPAGE 0
SET LINESIZE 132
SET PAGESIZE 55
CLEAR 	BREAKS;
BREAK ON OPERATOR SKIP 1

COLUMN OPERATOR HEADING 'Operator' FORMAT A12
COLUMN Well FORMAT A50
COLUMN STR FORMAT A18
COLUMN ELEVATION HEADING 'Elev' FORMAT 99999.99
COLUMN ELEVATION_REF HEADING 'Elev|Ref' FORMAT A4
COLUMN DRILLERS_TD HEADING 'TD' FORMAT 99999.99
COLUMN UWI HEADING 'UWI' FORMAT A20

TTITLE 	CENTER ' -->  --> &1 Well Header <--  <--' SKIP CENTER 'Sorted by Operator';

SELECT  A.OPERATOR, A.WELL_NAME||' #'||A.WELL_NUMBER Well, 
B.SECTION||'-'||B.TOWNSHIP||B.NORTH_SOUTH||'-'||B.RANGE||B.EAST_WEST STR,
A.ELEVATION, A.ELEVATION_REF, A.DRILLERS_TD,A.UWI
FROM 	&1..WELL_HDR A, &1..WELL_LOCATIONS B
WHERE	A.NODE_ID = B.NODE_ID(+)
ORDER BY A.OPERATOR, A.WELL_NAME, A.WELL_NUMBER;
