/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_STATS_SL.SQL */
/* *3    26-MAR-1990 11:43:07 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:57:18 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:45:46 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_STATS_SL.SQL */
SET NEWPAGE 0
SET LINESIZE 80
SET PAGESIZE 55
TTITLE '>------ FINDER WELL TOPS STATISTICS FOR WELLS IN CONTROL LIST &3 ------<'
select
A.UWI,
count(distinct form_code) "NUMBER OF PICKS" 
from &1..well_tops A, &2 C
WHERE A.UWI = C.UWI
group by A.uwi
order by count(distinct form_code) desc
/
