/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_WELLNAME.SQL */
/* *2    27-JUL-1990 07:42:16 DOROTHY "(SPR 5701) removed comma following 'well_locations b' to correct error." */
/* *1    24-MAY-1990 18:34:20 DOROTHY "REPORT SCRIPT FOR WELL HEADER TABLE" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_WELLNAME.SQL */

DOC
	ESI Well Header Report
	p1 = Project Name
	p2 = name of control list table
        p3 = name of original select list
#

CLEAR 	BREAKS;
BREAK ON OPERATOR SKIP 1

TTITLE 	CENTER ' -->  --> &1 Well Header Information Sorted by Well Name  <--  <--'
 
SET NEWPAGE 0
SET PAGESIZE 55
SET LINESIZE 132
SET SPACE 2

COLUMN OPERATOR HEADING 'Operator' FORMAT A25
COLUMN WELLNAME HEADING 'Well Name' FORMAT A30
COLUMN STR HEADING 'S-T-R-PM' FORMAT A15
COLUMN ELEVATION HEADING 'Elev.' FORMAT 99,999.99
COLUMN ELEVATION_REF HEADING 'Elev.|Ref.' FORMAT A5
COLUMN DRILLERS_TD HEADING 'Drillers|TD' FORMAT 99,999.99 JUS C
COLUMN UWI HEADING 'Unique Identifier' FORMAT A20

SELECT  
   A.OPERATOR, 
   A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME, 
   B.SECTION||'-'||B.TOWNSHIP||B.NORTH_SOUTH||'-'||B.RANGE||B.EAST_WEST||'-'||B.PRINCIPAL_MERIDIAN STR,
   A.ELEVATION,  
   A.ELEVATION_REF, 
   A.DRILLERS_TD,
   A.UWI
FROM 	
   &1..WELL_HDR A, 
   &1..WELL_LOCATIONS B
WHERE	
    A.NODE_ID = B.NODE_ID(+) 
ORDER BY 
   A.WELL_NAME, 
   A.WELL_NUMBER,  
   A.OPERATOR
/
