/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_SL.SQL */
/* *4    24-MAY-1990 20:58:13 DOROTHY "(SPR 5182) SHORTENED COLUMN SPECS FOR OPERATOR AND FORM_CODE." */
/* *3    26-MAR-1990 11:42:47 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:56:47 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:44:03 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_SL.SQL */
CLEAR 	BREAKS;
BREAK	ON WELLNAME ON OPERATOR ON UWI  SKIP 2;
SET NEWPAGE 0
SET LINESIZE 132
SET SPACE 3 
SET PAGES 55

COLUMN OPERATOR FORMAT A6 HEADING 'Operator';
COLUMN SOURCE FORMAT A10 HEADING 'Source';
COLUMN MD FORMAT 99,999.9 HEADING 'Meas.|Depth'
COLUMN FORM_CODE FORMAT A8 HEADING 'Formation'
COLUMN WELLNAME FORMAT A12 HEADING 'Well Name'
COLUMN LAST_UPDATE HEADING 'Last|Update'
COLUMN UWI HEADING 'Unique Identifier' FORMAT A20

TTITLE 	CENTER 	'&1 Tops Report Using Control List &3' SKIP CENTER 'Sorted by Well Name';

SELECT  
  A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME,
  A.UWI,   
  A.OPERATOR,
  D.FORM_CODE, 
  D.MD, 
  D.SOURCE, 
  D.LAST_UPDATE
FROM 	
  &1..WELL_TOPS D, 
  &1..WELL_HDR A,
  &2 B
WHERE	
  A.UWI = D.UWI
     AND
  A.UWI  = B.UWI 
ORDER BY A.WELL_NAME, A.WELL_NUMBER, D.MD, D.SOURCE;
