/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_NAME.SQL */
/* *3    26-MAR-1990 11:40:35 DOROTHY "(SPR -1) Schema fix." */
/* *2    26-JAN-1990 14:41:52 MING "(SPR 0) change A.UWI = B.NODE_ID to A.NODE_ID = B.NODE_ID for unique node_id" */
/* *1    19-JUN-1989 14:53:47 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_HDR_BY_NAME.SQL */
DOC
	ESI Well Header Report
	p1 = Project Name
	p2 = name of control list table
#

CLEAR 	BREAKS;

TTITLE 	CENTER ' -->  --> &1 Well Header <--  <--' SKIP CENTER 'Sorted by Well Name';

SELECT  A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME, A.OPERATOR,
B.SECTION||'-'||B.TOWNSHIP||B.NORTH_SOUTH||'-'||B.RANGE||B.EAST_WEST STR,
A.ELEVATION, A.ELEVATION_REF, A.DRILLERS_TD,A.UWI
FROM 	&1..WELL_HDR A, &1..WELL_LOCATIONS B
WHERE	A.NODE_ID = B.NODE_ID(+)
ORDER BY WELL_NAME, WELL_NUMBER;
