/* DEC/CMS REPLACEMENT HISTORY, Element WELL_LOG_TRACE_HDR.SQL */
/* *2    26-MAR-1990 11:41:13 DOROTHY "(SPR -1) Schema fix." */
/* *1    19-JUN-1989 14:53:57 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_LOG_TRACE_HDR.SQL */
SET PAGESIZE 55;
SET LINESIZE 131;
SET VERIFY OFF;
SET NEWPAGE 0;

TTITLE CENTER 'W E L L    L O G    T R A C E    D A T A B A S E    R E P O R T' -
       SKIP 2 -
       CENTER '&1 Project  ---  Sorted by Well, Source and Trace' -
       SKIP 4;

COLUMN VERSION FORMAT 99 HEADING 'VER';
COLUMN UWI  FORMAT A14 heading 'Unique Well ID'
COLUMN SERVICE FORMAT A7 HEADING 'Service'
COLUMN TOP  FORMAT 99999.9 HEADING 'Trace|Top' JUSTIFY CENTER;
COLUMN BASE FORMAT 99999.9 HEADING 'Trace|Bottom';
COLUMN DINC FORMAT 9.9 HEADING 'Sample|Incr.';
COLUMN DEPTH_UNIT FORMAT A7  HEADING 'Depth|Units';
COLUMN TRACE_MIN FORMAT 99999.99 HEADING 'Minimum|Value' JUSTIFY CENTER;
COLUMN TRACE_MAX FORMAT 99999.99 HEADING 'Maximum|Value' JUSTIFY CENTER;
COLUMN TRACE_UNIT FORMAT A5 HEADING 'Trace|Units';
COLUMN LAST_UPDATE HEADING 'Updated' JUSTIFY CENTER;
COLUMN UPDATED_BY FORMAT A10 HEADING 'Updated|By';

BREAK ON REPORT PAGE ON UWI SKIP 1;

SELECT A.UWI, SOURCE, TRACE, SERVICE, VERSION, TOP, BASE, DINC, DEPTH_UNIT, 
	TRACE_MIN, TRACE_MAX, TRACE_UNIT, LAST_UPDATE, UPDATED_BY
	FROM &1..WELL_LOG_TRACE_HDR A, TEMP_WELL_LISTS B
	WHERE A.UWI = KEY_UWI AND TEMP_LIST_NAME = '&2'
	ORDER BY A.UWI, SOURCE, TRACE;
