/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_BY_MD.SQL */
/* *3    26-MAR-1990 11:42:31 DOROTHY "(SPR -1) Schema fix." */
/* *2    26-JAN-1990 14:46:21 MING "(SPR 0) change A.UWI = B.NODE_ID to A.NODE_ID = B.NODE_ID for unique node_id" */
/* *1    19-JUN-1989 14:54:00 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_TOPS_BY_MD.SQL */
CLEAR 	BREAKS;
BREAK	ON WELLNAME ON OPERATOR ON UWI ON STR SKIP 1;
COLUMN OPERATOR FORMAT A20;
COLUMN SOURCE FORMAT A10;

TTITLE 	CENTER 	'&1 Tops Report Using Control List "&3"' SKIP CENTER 'SORTED BY WELL NAME';

SELECT  A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME,
B.SECTION||'-'||B.TOWNSHIP||B.NORTH_SOUTH||'-'||B.RANGE||B.EAST_WEST STR,
A.UWI, A.OPERATOR,D.FORM_CODE, D.MD, D.SOURCE, D.LAST_UPDATE
FROM 	&1..WELL_TOPS D, &1..WELL_HDR A, &1..WELL_LOCATIONS B, &2 C
WHERE	A.NODE_ID = B.NODE_ID(+) AND A.UWI = C.UWI AND A.UWI = D.UWI
ORDER BY A.WELL_NAME, A.WELL_NUMBER, D.MD, D.SOURCE;
