/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY_SL.SQL */
/* *5    20-AUG-1991 17:03:48 ERIC "(SPR 1) Fixed tablename problem plus general upgrade." */
/* *4    16-JUL-1990 18:40:42 ALLAWAY "(SPR -1) CHECKIN FOR 7-15-90 SCHEMA UPDATE" */
/* *3    26-MAR-1990 11:39:36 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:46:10 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:38:09 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY_SL.SQL */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY.SQL */
/* *3    16-JUL-1990 18:39:51 ALLAWAY "(SPR -1) CHECKIN FOR 7-15-90 SCHEMA UPDATE" */
/* *2    26-MAR-1990 11:39:17 DOROTHY "(SPR -1) Schema fix." */
/* *1    19-JUN-1989 14:53:45 SYSTEM "" */
/* DEC/CMS REPLACEMENT HISTORY, Element WELL_CHECKSHOT_SURVEY.SQL */
DOC
	ESI Well Checkshot Survey Report
	p1 = Project Name
	p2 = name of control list table
        p3 = name of original select list
#

CLEAR 	BREAKS;

BREAK ON WELLNAME SKIP 1 -
ON UWI NODUP

SET NEWPAGE 0
SET PAGESIZE 55
SET LINESIZE 100
SET SPACE 3

COLUMN MD FORMAT 99,999.9 HEADING 'Measured|Depth'
COLUMN TIME FORMAT 9999.9 HEADING 'Time'
COLUMN UWI FORMAT A17 HEADING 'UWI'
COLUMN WELLNAME FORMAT A30 HEADING 'Well Name'
COLUMN SOURCE FORMAT A14 HEADING 'Source'
COLUMN TIME_UNIT FORMAT A8 HEADING 'Time|Unit'

TTITLE 	' -->  --> Project &1 Well Checkshot Survey Report -
Restricted By Select List &3 <--  <-- '

SELECT  
	A.WELL_NAME||' #'||A.WELL_NUMBER WELLNAME, 
	A.UWI,
	SOURCE,
	MD, 
	TIME,
	TIME_UNIT
FROM 	
	&1..WELL_HDR A, 
	&1..WELL_CHECKSHT_SRVY B,
	&2 C
WHERE	
	A.UWI = B.UWI
AND
	A.UWI = C.UWI 
ORDER BY 
	A.WELL_NAME, 
	A.WELL_NUMBER, 
	MD;
