/* DEC/CMS REPLACEMENT HISTORY, Element FM_STATS.SQL */
/* *3    14-JUN-1991 13:54:20 ERIC "(SPR 1) Wrote sql; previous file zero size." */
/* *2    18-DEC-1990 08:36:58 ERIC "(SPR -1) new report" */
/* *1     7-DEC-1990 15:31:54 ERIC "Summary of scatter, grid, data, and perspective files for a project." */
/* DEC/CMS REPLACEMENT HISTORY, Element FM_STATS.SQL */
/* DEC/CMS REPLACEMENT HISTORY, Element sgcp_summ.sql */
/* *1    13-JUN-1991 09:15:46 Sheehy "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element sgcp_summ.sql */
SET LONG 1024;
SET PAGESIZE 55;
SET LINESIZE 132;
SET SPACE 2
SET VERIFY OFF;
SET NEWPAGE 0;

TTITLE CENTER 'GRID, CONTOUR AND SCATTER FILES REFERENCED BY &1 MAP DEFINITIONS' -
       SKIP 2 -
       CENTER ' Sorted by Map Name' -
       SKIP 4;

COLUMN MAP_NAME FORMAT A40 HEADING 'Map Name';
COLUMN PARAMETER FORMAT A38 HEADING 'File Name';
COLUMN KEYWORD FORMAT A40 HEADING 'File Type';

CLEAR BREAKS;
BREAK ON MAP_NAME SKIP 1 ON KEYWORD DUP;

SELECT MAP_NAME, PARAMETER,
	KEYWORD
	FROM &1..MAP_OVERLAYS
	WHERE KEYWORD = 'XYZ FILE'
		OR KEYWORD = 'GRID FILE: INPUT'
		OR KEYWORD = 'GRID FILE: OUTPUT'
		OR KEYWORD = 'CONTOUR FILE: INPUT'
		OR KEYWORD = 'CONTOUR FILE: OUTPUT'
	ORDER BY MAP_NAME
/
