$! DEC/CMS REPLACEMENT HISTORY, Element LD_RUN_TOBIN_LOADER.COM
$! *1    19-JUN-1989 14:57:17 SYSTEM ""
$! DEC/CMS REPLACEMENT HISTORY, Element LD_RUN_TOBIN_LOADER.COM
$ ! COMMAND PROCEDURE TO INVOKE THE TOBIN DATA LOADER FOR FINDER
$ ! THE ARGUMENTS ARE GENERATED WITHIN FINDER AND CAN BE IN ANY ORDER
$ !
$ TOBIN_LOADER :== $ESI$BIN:LD_TOBIN_LOADER
$ TOBIN_LOADER 'P1' 'P2' 'P3' 'P4' 'P5' 'P6' 'P7' 'P8'
