REMARK This sql command file contains various physical database schema
REMARK changes deemed beneficial for WHCS loading.

DROP INDEX LOADER_WELL_LOCS_UWI;     
DROP INDEX LOADER_WELL_TOPS_UWI;     
DROP INDEX NODES_NODE_X;             
DROP INDEX NODES_NODE_Y;             
DROP INDEX WELL_CMPT_ANAL_UWI;       
DROP INDEX WELL_CMPT_GAUGE_UWI;      
DROP INDEX WELL_COMPLETIONS_UWI;     
DROP INDEX WELL_CORE_OVERLAPS_UWI;   
DROP INDEX WELL_CORE_OVRLP_FORM;     
DROP INDEX WELL_CRD_VISCOSITY_UWI;   
DROP INDEX WELL_HDR_CRSTATUS;        
DROP INDEX WELL_HDR_NODE_ID;         
DROP INDEX WELL_HDR_OPERATOR;        
DROP INDEX WELL_HDR_SECOND_NODE_ID;  
DROP INDEX WELL_HDR_WELL_NAME;       
DROP INDEX WELL_LOG_CURVE_HDR_TRACE; 
DROP INDEX WELL_MISC_DATA_UWI;       
DROP INDEX WELL_PROD_FIELD_DATA_UWI; 
DROP INDEX WELL_SHOWS_UWI;           
DROP INDEX WELL_TEST_VO_PRESS_UWI;   
DROP INDEX WELL_TOPS_FORM_CODE;

remark The alter tables are very important for efficiency in the load
remark process.

ALTER TABLE WELL_HDR PCTFREE 50;
ALTER TABLE LOADER_CORE_HDR PCTFREE 10;      
ALTER TABLE WELL_FORM_TEST_HDR PCTFREE 10;
/* DEC/CMS REPLACEMENT HISTORY, Element LD_WHCS_ALTER_SCHEMA.SQL*/
/* *2    13-MAY-1991 12:36:24 LOEBL "(SPR 0) Initial version "*/
/* *1    13-MAY-1991 12:35:09 LOEBL "Physical Database Schema Alterations for WHCS Load"*/
/* DEC/CMS REPLACEMENT HISTORY, Element LD_WHCS_ALTER_SCHEMA.SQL*/
