/* DEC/CMS REPLACEMENT HISTORY, Element LD_WHCS_FIX_TABLES.SQL */
/* *7    13-MAY-1991 12:37:08 LOEBL "(SPR 0) Bug fixes for WHCS loader v6.2" */
/* *6    21-DEC-1990 14:32:43 ALLAWAY "(SPR 5528) PERFORMANCE OVERHAUL" */
/* *5     7-NOV-1990 11:14:26 ALLAWAY "(SPR 5528) FIX MINOR SYNTAX ERRORS" */
/* *4    16-JUL-1990 18:38:15 ALLAWAY "(SPR -1) CHECKIN FOR 7-15-90 SCHEMA UPDATE" */
/* *3    23-APR-1990 14:26:58 PURNA "(SPR 0) Dorothy's enron mods" */
/* *2     6-APR-1990 17:05:45 ALLAWAY "(SPR -1) new file to fix some tables without schema changes" */
/* *1     6-APR-1990 17:04:26 ALLAWAY "used to ensure that certain tables have wide enough columns for the loader" */
/* DEC/CMS REPLACEMENT HISTORY, Element LD_WHCS_FIX_TABLES.SQL */
DOC;
These operations need to be performed on these tables in some existing
installations where the database schema pre-dates 4/3/90...
#
ALTER TABLE LOADER_CORE_ANAL MODIFY(
	TOP NUMBER(10,2));
ALTER TABLE LOADER_CORE_ANAL MODIFY(
	DEPTH NUMBER(10,2));

ALTER TABLE LOADER_WELL_LOCATIONS MODIFY(
	NODE_ID NUMBER(10) );
ALTER TABLE LOADER_WELL_LOCATIONS MODIFY(
	SECTION NUMBER(4,1));
ALTER TABLE LOADER_WELL_LOCATIONS MODIFY(
	TOWNSHIP NUMBER(5,1));
ALTER TABLE LOADER_WELL_LOCATIONS MODIFY(
	RANGE NUMBER(5,1));

ALTER TABLE WELL_LOCATIONS MODIFY(
	SECTION NUMBER(4,1));
ALTER TABLE WELL_LOCATIONS MODIFY(
	TOWNSHIP NUMBER(5,1));
ALTER TABLE WELL_LOCATIONS MODIFY(
	RANGE NUMBER(5,1));

ALTER TABLE WELL_SHOWS MODIFY(
	TEST_NO		CHAR(4) );
ALTER TABLE WELL_SHOWS MODIFY(
	TEST_TYPE	CHAR(12) );

ALTER TABLE WELL_HDR ADD(
	RIG_NO		CHAR(6) );
ALTER TABLE WELL_HDR ADD(
	CONTRACTOR	CHAR(20) );

ALTER TABLE LOADER_WELL_HDR ADD(
	RIG_NO		CHAR(6) );
ALTER TABLE LOADER_WELL_HDR ADD(
	CONTRACTOR	CHAR(20) );

ALTER TABLE WELL_HDR_SECOND ADD(
	RIG_NO		CHAR(6) );
ALTER TABLE WELL_HDR_SECOND ADD(
	CONTRACTOR	CHAR(20) );

ALTER TABLE WELL_HDR MODIFY(
	OPERATOR	CHAR(30) );
ALTER TABLE WELL_HDR MODIFY(
	PROV_ST		CHAR(8) );
ALTER TABLE WELL_HDR MODIFY(
	FLDPOOLWILD	CHAR(18) );

ALTER TABLE LOADER_WELL_HDR MODIFY(
	OPERATOR	CHAR(30) );
ALTER TABLE LOADER_WELL_HDR MODIFY(
	PROV_ST		CHAR(8) );
ALTER TABLE LOADER_WELL_HDR MODIFY(
	FLDPOOLWILD	CHAR(18) );

ALTER TABLE WELL_HDR_SECOND MODIFY(
	OPERATOR	CHAR(30) );
ALTER TABLE WELL_HDR_SECOND MODIFY(
	PROV_ST		CHAR(8) );
ALTER TABLE WELL_HDR_SECOND MODIFY(
	FLDPOOLWILD	CHAR(18) );

remark 
remark the following alterations are for
remark projects previous to Finder version 6.3
remark 
ALTER TABLE WELL_PROD_TEST_HDR MODIFY
       ( GAS_FLOW NUMBER(8,1) );

ALTER TABLE WELL_OIL_ANAL_HDR MODIFY
       ( GOR NUMBER(10,4) );

ALTER TABLE WELL_PRESS_AOF MODIFY
       ( AOFP NUMBER(10,2) );



exit;
