*T MENU
,500
*N XS_LAYOUT_MENU
*S PR 0 PU 1
CrossSection
12 D M FINDER/GEOLOGIC_INTERPRETATION/CROSSSECTION
*I NEW_MENU_ITEM
New Layout
*I RETRIEVE_MENU_ITEM
Retrieve Layout
*I SAVE_MENU_ITEM
Save Layout
*I DELETE_MENU_ITEM
Delete Layouts
*I DASH_1_MENU_ITEM
(-
*I PREVIEW_MENU_ITEM
(Preview Layout/V
*I DRAW_MENU_ITEM
Retrieve Data & Draw/D
*I REDRAW_MENU_ITEM
ReDraw/G
*I PLOT_MENU_ITEM
Send to Plotter/P
*I PLOT_LAYOUT_ITEM
Plot layout
*I DASH_2_MENU_ITEM
(-
*I QUIT_XS_MENU_ITEM
Quit/Q

*T MENU
,502
*N XS_EDIT_MENU
*S PR 0 PU 1
Preferences
12 D M FINDER/GEOLOGIC_INTERPRETATION/PREFERENCES
*I CHANGE_ALL_MENU_ITEM
Review-Change All
*I STOP_ALL_MENU_ITEM
Stop Review Sequence
*I DIVIDING_LINE_ITEM
(-
*I TITLE_BLOCK_ITEM
Title Block
*I TYPE_MENU_ITEM
Cross Section Parameters
*I HORIZ_SCALE_MENU_ITEM
Horizontal Scale
*I LOG_HEADER_MENU_ITEM
Log Header Items
*I DEPTH_SCALE_MENU_ITEM
Depth Scale
*I INTERVAL_MENU_ITEM
Depth Interval
*I TRACK_DEF_MENU_ITEM
Track Definition
*I TRACE_SEL_MENU_ITEM
Trace Selection
*I TRACE_ATT_MENU_ITEM
Trace Attributes

*T MENU
,504
*N XS_WELLS_MENU
*S PR 0 PU 1
Wells
5 D M FINDER/GEOLOGIC_INTERPRETATION/WELLS
*I CURRENT_LIST_MENU_ITEM
Use Current Global Well List
*I DIG_TRAVERSE_MENU_ITEM
Digitize Traverse
*I SAVE_TRAVERSE_MENU_ITEM
Save Traverse
*I RETV_TRAVERSE_MENU_ITEM
Retrieve Traverse
*I SHOW_WELLS_MENU_ITEM
Show Well List

*T MENU
,506
*N XS_TOPS_MENU
*S PR 0 PU 1
Tops
4 D M FINDER/GEOLOGIC_INTERPRETATION/TOPS
*I RETV_TOPS_MENU_ITEM
Retrieve Tops
*I DISPLAY_TOPS_MENU_ITEM
Display Tops
*I DIG_TOPS_MENU_ITEM
Digitize Tops
*I SAVE_TOPS_MENU_ITEM
Save Tops

