/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_FORM_CODE.SQL */
/* *4    24-MAY-1990 20:46:23 DOROTHY "(SPR 5182) UPDATED PER CHANGES TO DATABASE TABLE." */
/* *3    26-MAR-1990 11:38:19 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:41:08 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:30:41 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_FORM_CODE.SQL */
SET NEWPAGE 0
SET LINES 75
SET PAGES 55

TTITLE '&1 Project Formation Picks Sorted by Minimum Measured Depth'
 
COLUMN WELLS HEADING '# of Wells'

SELECT 
   FORM_CODE "Formation",  
   min(md),max(md),count(*) WELLS
FROM &1..WELL_TOPS
GROUP BY FORM_CODE
ORDER BY min(md)
/
