/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_NUMBER.SQL */
/* *4    14-JUN-1991 13:14:18 ERIC "(SPR 1) Reformatted" */
/* *3    26-MAR-1990 11:38:47 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:43:28 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:34:06 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_NUMBER.SQL */
SET NEWPAGE 0
SET LINES 80
SET PAGES 55

TTITLE 'Number of &1 Project Wells Having Formation Picks'
 
COLUMN WELLS HEADING '# of Wells'

SELECT 
   FORM_CODE "Formation",  
   COUNT(DISTINCT UWI) WELLS
FROM &1..WELL_TOPS
GROUP BY FORM_CODE
ORDER BY COUNT(DISTINCT UWI) DESC
/
