/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_FORM_CODE_SL.SQL */
/* *4    24-MAY-1990 20:47:47 DOROTHY "(SPR 55182) UPDATED PER CHANGES TO DATABASE TABLE." */
/* *3    26-MAR-1990 11:38:33 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:42:24 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:32:05 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element TOPS_BY_FORM_CODE_SL.SQL */
SET NEWPAGE 0
SET LINES 80
SET PAGES 132

TTITLE '&1 Project Formation Picks Using Control List &2'
 
COLUMN WELLS HEADING '# of Wells'

SELECT 
   FORM_CODE "Formation",
   MIN(MD),MAX(MD),  
   COUNT(*) WELLS
FROM &1..WELL_TOPS A, &2 B
WHERE A.UWI = B.UWI
GROUP BY FORM_CODE
ORDER BY MIN(MD)
/
