/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_DEL_SINGLE_WELL.SQL */
/* *2    17-JUL-1991 14:42:14 ALLAWAY "(SPR 8648) initial checkin" */
/* *1    17-JUL-1991 14:37:29 ALLAWAY "DBA example utility script" */
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_DEL_SINGLE_WELL.SQL */
rem utdba_del_single_well.sql

SET HEAD OFF;
SET FEED OFF;
SET LINESIZE 80;
SET PAGESIZE 10000;
SPOOL DEL_&1..SQL;
SELECT 'PROMPT Deleting data for well &1 from table '||TNAME||'...',
'DELETE '||TNAME||' WHERE UWI = ''&1'';'
FROM ESI.FINDER_TABLES WHERE TNAME IN(
SELECT DISTINCT TNAME FROM ESI.FINDER_COLUMNS WHERE DOMAIN = '1');
SPOOL OFF;
START DEL_&1..SQL
