SET HEAD OFF
SET FEED OFF
SET VERIFY OFF
SET PAGESIZE 10000
SPOOL DEL_FM_FILES.COM;
PROMPT $ SET NOON
PROMPT $ SET VERIFY
select '$ DELETE/LOG '||OS_PATHNAME
FROM &1..FM_HDR WHERE EXPIRATION_DATE < SYSDATE
AND EXPIRATION_DATE IS NOT NULL
/
PROMPT $ SET NOVERIFY
SPOOL OFF;
SPOOL DEL_FM_DB_RECS.SQL;
select 'DELETE &1..FM_HDR WHERE FILE_ID = '||FILE_ID||';',
'DELETE &1..GC_FILE_HDR WHERE FILE_ID = '||FILE_ID||';'
FROM &1..FM_HDR WHERE EXPIRATION_DATE < SYSDATE
AND EXPIRATION_DATE IS NOT NULL
/
SPOOL OFF
