SELECT UWI,FORM_CODE,SOURCE FROM WELL_TOPS
GROUP BY UWI,FORM_CODE,SOURCE
HAVING COUNT(*) > 1;

/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_FIND_DUP_TOPS.SQL*/
/* *2    17-JUL-1991 14:42:26 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:34:56 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_FIND_DUP_TOPS.SQL*/
