rem utdba_hdr_to_dir_srvy.sql

INSERT INTO WELL_DIR_SRVY_PTS (UWI,SOURCE,SURVEY_NO,MD,TVD,DX,DY)
SELECT UWI,'HEADER','1',DRILLERS_TD,TVD,BASE_DELTA_X,BASE_DELTA_Y
FROM WELL_HDR 
WHERE UWI IN (SELECT DISTINCT H.UWI
              FROM WELL_HDR H,WELL_DIR_SRVY_PTS D
              WHERE H.UWI=D.UWI
              AND MD IS NULL OR
              DRILLERS_TD > (SELECT MAX(MD) FROM WELL_DIR_SRVY_PTS
              WHERE UWI = H.UWI));
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_HDR_TO_DIR_SRVY.SQL*/
/* *2    17-JUL-1991 14:42:30 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:38:55 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_HDR_TO_DIR_SRVY.SQL*/
