rem utdba_create_plot_sym_wells.sql

SET HEAD OFF;
SET PAGESIZE 1000;
SPOOL PS_INSERT.SQL;
SELECT 'INSERT INTO WELL_HDR (UWI,NODE_ID,PLOT_SYMBOL,PRIMARY_SOURCE)
VALUES (''PS'||ROWNUM||''','||ESI.LYNX_ID_SEQ.NEXTVAL||
','||ROWNUM||',''TEST'');',
'INSERT INTO NODES (NODE_ID,NODE_X,NODE_Y,LOC_QUAL) 
VALUES ('||ESI.LYNX_ID_SEQ.CURRVAL||
','||(ROWNUM-(ROUND(ROWNUM/10-.51)*10))||'00,'||
(2000-(ROUND(ROWNUM/10-.51)*100))||',''A'');'
FROM WELL_HDR WHERE ROWNUM < 101;
SPOOL OFF
START PS_INSERT.SQL
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_CREATE_PLOT_SYM_WELLS.SQL*/
/* *2    17-JUL-1991 14:42:06 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:36:53 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_CREATE_PLOT_SYM_WELLS.SQL*/
