rem utdba_comp_hdr_srvy.sql

SELECT D.UWI,DRILLERS_TD DTD,H.TVD,BASE_DELTA_X HDX,BASE_DELTA_Y HDY,
MD,D.TVD,DX,DY,SURVEY_NO
FROM WELL_HDR H,WELL_DIR_SRVY_PTS D
WHERE H.UWI=D.UWI
AND MD = (SELECT MAX(MD) FROM WELL_DIR_SRVY_PTS S WHERE S.UWI = D.UWI);
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_COMP_HDR_SRVY.SQL*/
/* *2    17-JUL-1991 14:41:58 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:36:19 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_COMP_HDR_SRVY.SQL*/
