DOC
...Deleting from the TEXT table.;
#
DELETE FROM TEXT WHERE TEXT_ID IN
   (SELECT GOC.ITEM_ID
      FROM
	 GRAPHIC_OBJECT_CORRELATIONS GOC,
	 GRAPHIC_OBJECTS GO
      WHERE
	 GO.OBJECT_ID = GOC.OBJECT_ID  AND
	 GOC.ITEM_CLASS = 'TEXT'       AND
	 GO.OBJECT_NAME = 'FAULTS');

DOC
...Deleting from the LINES table.;
#
DELETE FROM LINES WHERE LINE_ID IN
   (SELECT GOC.ITEM_ID
      FROM
	 GRAPHIC_OBJECT_CORRELATIONS GOC,
	 GRAPHIC_OBJECTS GO
      WHERE
	 GO.OBJECT_ID = GOC.OBJECT_ID  AND
	 GOC.ITEM_CLASS = 'LINE'       AND
	 GO.OBJECT_NAME = 'FAULTS');

DOC
...Deleting from the GRAPHIC_OBJECT_CORRELATIONS table.;
#
DELETE FROM GRAPHIC_OBJECT_CORRELATIONS WHERE OBJECT_ID IN
   (SELECT OBJECT_ID
      FROM  GRAPHIC_OBJECTS
      WHERE OBJECT_NAME = 'FAULTS');

DOC
...Deleting from the GRAPHIC_OBJECTS table.;
#
DELETE FROM GRAPHIC_OBJECTS WHERE OBJECT_NAME = 'FAULTS';

DOC
...Deleting from the GRAPHIC_OBJECT_CODES table.;
#
DELETE FROM GRAPHIC_OBJECT_CODES WHERE NAME = 'FAULTS';

DOC                
...Deleting the SEIS_FAULT_TRACE table.
#
DELETE FROM SEIS_FAULT_TRACE;
DOC
Don't forget to delete the nlist files associated with the faults in the 
project SEISMIC.FTRACE directory.
#
EXIT

/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_GO_DELETE_FAULTS.SQL*/
/* *2    16-AUG-1991 14:25:40 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    16-AUG-1991 14:24:39 ALLAWAY "Delete fault polygons out of the graphic object database."*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_GO_DELETE_FAULTS.SQL*/
