rem utdba_stat_cod_frm_hdr.sql

INSERT INTO CODES.WELL_STATUS_CODES(STATUS)
SELECT DISTINCT CRSTATUS FROM WELL_HDR
WHERE CRSTATUS NOT IN (SELECT STATUS FROM CODES.WELL_STATUS_CODES);
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_STAT_COD_FRM_HDR.SQL*/
/* *2    17-JUL-1991 14:42:33 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:35:36 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_STAT_COD_FRM_HDR.SQL*/
