rem utdba_ck_valid_status.sql

SELECT DISTINCT STATUS FROM WELL_HDR 
WHERE STATUS NOT IN (SELECT STATUS 
FROM CODES.WELL_STATUS_CODES);

/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_CK_VALID_STATUS.SQL*/
/* *2    17-JUL-1991 14:41:52 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:31:42 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_CK_VALID_STATUS.SQL*/
