/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_UPDATE_PLOT_SYM.SQL */
/* *3    26-AUG-1991 09:20:09 ALLAWAY "(SPR 3869) fix incorrect field name in script" */
/* *2    17-JUL-1991 14:42:37 ALLAWAY "(SPR 8648) initial checkin" */
/* *1    17-JUL-1991 14:39:41 ALLAWAY "DBA example utility script" */
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_UPDATE_PLOT_SYM.SQL */
rem utdba_update_plot_sym.sql

UPDATE WELL_HDR 
SET PLOT_SYMBOL = (SELECT SYMBOL FROM 
CODES.WELL_STATUS_CODES WHERE WELL_HDR.CRSTATUS = 
CODES.WELL_STATUS_CODES.STATUS) 
WHERE WELL_HDR.CRSTATUS IS NOT NULL 
AND PLOT_SYMBOL IS NULL;
