CREATE TABLE TEMP AS
SELECT UWI,FORM_CODE,SOURCE,MIN(ROWNUM) FROM WELL_TOPS 
GROUP BY UWI,FORM_CODE,SOURCE
HAVING COUNT(*) > 1;

DELETE WELL_TOPS
WHERE ROWNUM IN (SELECT ROWNUM FROM TEMP);
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_DEL_DUP_TOPS.SQL*/
/* *2    17-JUL-1991 14:42:10 ALLAWAY "(SPR 8648) initial checkin"*/
/* *1    17-JUL-1991 14:33:08 ALLAWAY "DBA example utility script"*/
/* DEC/CMS REPLACEMENT HISTORY, Element UTDBA_DEL_DUP_TOPS.SQL*/
