/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATISTICS_SL.SQL */
/* *4    18-DEC-1990 09:41:05 ERIC "(SPR -1) coorected for schema change (source)." */
/* *3    29-NOV-1990 09:13:11 ERIC "(SPR -1) no change" */
/* *2     4-AUG-1990 15:55:22 DOROTHY "(SPR 5738) seismic report script" */
/* *1     4-AUG-1990 15:49:47 DOROTHY "seismic report script" */
/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATISTICS_SL.SQL */
TTITLE 'Seismic Interpretation Statistics for Project &1 Using Control List &3'

SET NEWPAGE 0
SET LINES 132
SET PAGES 55
SET SPACE 2

BREAK ON SURVEY ON LINE_NAME SKIP 2

COL LINE_NAME FORMAT A12 HEADING 'Line Name'
COL SURVEY FORMAT A20 HEADING 'Survey Name'
COL SURFACE_CODE FORMAT A15 HEADING 'Horizon Name'
COL SOURCE HEADING 'Source' FORMAT A10
COL VERSION FORMAT 99 HEADING 'Vers'
COL FIRST_CDP FORMAT 9999 HEADING 'First|CDP #'
COL LAST_CDP FORMAT 9999 HEADING 'Last|CDP #'

SELECT
	C.LINE_NAME,
	C.SURVEY,
	SURFACE_CODE,
	A.SOURCE,
	VERSION,
	FIRST_CDP,
	LAST_CDP
FROM
	&1..SEIS_SURFACE A, &2 B, &1..SEIS_LINE_HDR C
WHERE
	C.LINE_ID = B.LINE_ID
	AND
	A.LINE_ID = C.LINE_ID
ORDER BY
	C.SURVEY,
	C.LINE_NAME,
	SURFACE_CODE,
	A.SOURCE,
	VERSION
/
