/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATS_SL.SQL */
/* *3    26-MAR-1990 11:38:04 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:39:34 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:26:52 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATS_SL.SQL */
TTITLE 'Seismic Interpretation Statistics for Project &1 Using Control List &3'

SET NEWPAGE 0
SET LINES 132
SET PAGES 55
SET SPACE 2

BREAK ON SURVEY ON LINE_NAME SKIP 2

COL LINE_NAME FORMAT A12 HEADING 'Line Name'
COL SURVEY FORMAT A20 HEADING 'Survey Name'
COL SURFACE_CODE FORMAT A15 HEADING 'Horizon Name'
COL SOURCE HEADING 'Source' FORMAT A10
COL VERSION  FORMAT 99 HEADING 'Vers'
COL FIRST_CDP_PICK FORMAT 9999 HEADING 'First|CDP#'
COL LAST_CDP_PICK FORMAT 9999 HEADING 'Last|CDP#'

SELECT
   C.LINE_NAME, 
   C.SURVEY,
   SURFACE_CODE,
   SOURCE,
   VERSION,
   FIRST_CDP_PICK, 
   LAST_CDP_PICK
FROM 
   &1..SEIS_SURFACE A,  &2 B,&1..SEIS_LINE_HDR C
WHERE
   C.LINE_NAME = B.LINE_NAME
              AND
   C.LINE_ID = A.LINE_ID
	AND
   NVL(A.SURVEY,'NULL') = NVL(B.SURVEY, 'NULL')
ORDER BY 
   C.SURVEY, 
   C.LINE_NAME,
   SURFACE_CODE,
   SOURCE,
   VERSION
/
