/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATISTICS.SQL */
/* *3    18-DEC-1990 10:50:13 ERIC "(SPR -1) fixed ambiguous source problem." */
/* *2     4-AUG-1990 15:49:15 DOROTHY "(SPR 5738) seismic report script" */
/* *1     4-AUG-1990 15:48:24 DOROTHY "sesimic report script" */
/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATISTICS.SQL */
TTITLE 'Seismic Interpretation Statistics for Project &1'

SET NEWPAGE 0
SET LINES 132
SET PAGES 55
SET SPACE 2

BREAK ON SURVEY ON LINE_NAME SKIP 2

COL LINE_NAME FORMAT A12 HEADING 'Line Name'
COL SURVEY FORMAT A20 HEADING 'Survey Name'
COL SURFACE_CODE FORMAT A15 HEADING 'Horizon Name'
COL SOURCE HEADING 'Source' FORMAT A10
COL VERSION FORMAT 99 HEADING 'Vers'
COL FIRST_CDP FORMAT 9999 HEADING 'First|CDP #'
COL LAST_CDP FORMAT 9999 HEADING 'Last|CDP #'

SELECT
	C.LINE_NAME,
	C.SURVEY,
	SURFACE_CODE,
	A.SOURCE,
	VERSION,
	FIRST_CDP,
	LAST_CDP
FROM
	&1..SEIS_SURFACE A, &1..SEIS_LINE_HDR C
WHERE
	A.LINE_ID = C.LINE_ID
ORDER BY
	C.SURVEY,
	C.LINE_NAME,
	SURFACE_CODE,
	A.SOURCE,
	VERSION
/
