/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_TIE.SQL */
/* *3    24-SEP-1990 17:17:38 GILLESPIE "Beta Deltas" */
/* *2     4-AUG-1990 15:25:41 DOROTHY "(SPR 5738) New seismic report" */
/* *1     4-AUG-1990 12:23:06 DOROTHY "seismic intersection report scripts" */
/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_TIE.SQL */
CLEAR BREAKS;
SET SPACE 1
SET NEWPAGE 0
SET LINESIZE 130
SET PAGESIZE 55
TTITLE '>------ &1 Seismic Line Intersection Information ------<'
COL THIS_LINE_ID HEADING 'This|Line'  FORMAT 999999
COL THIS_SHOT HEADING 'Shot|#' FORMAT 9999
COL TIE_LINE_ID HEADING 'Tie|Line' FORMAT 999999
COL TIE_SHOT HEADING 'Shot|#' FORMAT 9999
COL TIE_X HEADING 'X-Coord' FORMAT 99,999,999.9
COL TIE_Y HEADING 'Y-Coord' FORMAT 99,999,999.9
COL SURVEY HEADING 'Survey' FORMAT A8;
COL LINE_NAME FORMAT A8 HEADING 'Line|Name'
COL TIE_SURV FORMAT A8 HEADING 'Tie|Survey'
COL TIE_LIN FORMAT A8 HEADING 'Tie|line'
BREAK ON SURVEY DUP ON LINE_NAME DUP SKIP
SELECT
H.SURVEY,
H.LINE_NAME,
THIS_LINE_ID, 
THIS_SHOT,
J.SURVEY TIE_SURV,
J.LINE_NAME TIE_LIN,
TIE_LINE_ID, 
TIE_SHOT, 
TIE_X,
TIE_Y
FROM &1..FULL_TIE A, &1..SEIS_LINE_HDR H,&1..SEIS_LINE_HDR J
WHERE A.THIS_LINE_ID = H.LINE_ID
AND A.TIE_LINE_ID = J.LINE_ID
ORDER BY H.SURVEY,H.LINE_NAME,THIS_SHOT
/
