/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATS.SQL */
/* *4    26-NOV-1990 12:11:27 ERIC "(SPR 1) Corrected ambiguous source problem due to schema change seis_line_hdr." */
/* *3    26-MAR-1990 11:37:45 DOROTHY "(SPR -1) Schema fix." */
/* *2    29-SEP-1989 12:38:27 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:24:47 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element SEIS_INTERP_STATS.SQL */
TTITLE 'Seismic Interpretation Statistics for Project &1'

SET NEWPAGE 0
SET LINES 132
SET PAGES 55
SET SPACE 2

BREAK ON SURVEY ON LINE_NAME SKIP 2

COL LINE_NAME FORMAT A12 HEADING 'Line Name'
COL SURVEY FORMAT A20 HEADING 'Survey Name'
COL SURFACE_CODE FORMAT A15 HEADING 'Horizon Name'
COL SOURCE HEADING 'Source' FORMAT A10
COL VERSION  FORMAT 99 HEADING 'Vers'
COL FIRST_CDP FORMAT 9999 HEADING 'First|CDP#'
COL LAST_CDP FORMAT 9999 HEADING 'Last|CDP#'

SELECT
   LINE_NAME, 
   SURVEY,
   SURFACE_CODE,
   S.SOURCE,
   VERSION,
  FIRST_CDP, 
   LAST_CDP
FROM 
   &1..SEIS_SURFACE S,&1..SEIS_LINE_HDR H
WHERE
	S.LINE_ID = H.LINE_ID
ORDER BY 
   SURVEY, 
   LINE_NAME,
   SURFACE_CODE,
   S.SOURCE,
   VERSION
/
