/* DEC/CMS REPLACEMENT HISTORY, Element SELECT_LIST_REPORT.SQL */
/* *4    20-AUG-1991 15:52:11 ERIC "(SPR 1) Improved formatting." */
/* *3    24-MAY-1990 21:17:30 DOROTHY "(SPR 5281) UPDATE PER DATABASE TABLE CHANGES." */
/* *2    29-SEP-1989 12:40:00 ALLAWAY "(SPR 5011) SQL SCRIPT FOR FINDER REPORTS - NEW SCHEMA" */
/* *1    29-SEP-1989 11:28:19 ALLAWAY "SQL SCRIPT FOR FINDER REPORTS" */
/* DEC/CMS REPLACEMENT HISTORY, Element SELECT_LIST_REPORT.SQL */
SET SPACE 2
SET NEWPAGE 0
SET LINESIZE 132
SET PAGES 55

COL SOURCE NOPRINT NEW_VAL SOURCE_VAR
COL TODAY NOPRINT NEW_VAL DATE_VAR
COL NAME FORMAT A30 HEADING 'Select List Name'
COL REMARKS FORMAT A40 WORD_WRAP HEADING 'Description'
COL NITEMS FORMAT 9,999 HEADING '# Items'
COL DATA_TYPE FORMAT A14 HEADING 'Type' TRUNC
COL LAST_UPDATE FORMAT A9 HEADING 'Created'
COL LAST_REFERENCE FORMAT A9 HEADING 'Last Used'
COL EXPIRATION_DATE FORMAT A9 HEADING 'Expires'

BREAK ON SOURCE SKIP PAGE ON DATA_TYPE SKIP 2

TTITLE CENTER 'Select List Report for Project &1' SKIP 2 -
   LEFT 'Creator:  ' SOURCE_VAR   RIGHT 'Report Date: ' DATE_VAR  SKIP2

SELECT 
   TO_CHAR(SYSDATE, 'MM/DD/YYYY') TODAY,
   SOURCE,
   DATA_TYPE,
   NAME,
   REMARKS, 
   NITEMS,
   LAST_UPDATE,
   LAST_REFERENCE,
   EXPIRATION_DATE
FROM &1..SLIST_HDR
ORDER BY 
   SOURCE, 
   DATA_TYPE,
   NAME,
   EXPIRATION_DATE DESC
/
