$! DEC/CMS REPLACEMENT HISTORY, Element SET_JOB_LOGICAL.COM
$! *1    13-NOV-1990 11:23:53 VINCE "initial release"
$! DEC/CMS REPLACEMENT HISTORY, Element SET_JOB_LOGICAL.COM
$! DEC/CMS REPLACEMENT HISTORY, Element SET_JOB_LOGICAL.COM
$! *1     6-MAR-1990 08:50:29 GILLESPIE "initial release"
$! DEC/CMS REPLACEMENT HISTORY, Element SET_JOB_LOGICAL.COM
$ ! P1 = LOGICAL NAME TO SET
$ ! P2 = FILE NAME TO SEARCH FOR
$ !
$ FILENAME = F$SEARCH("''P2'")
$ DEFINE/JOB 'P1' 'FILENAME'
