$! DEC/CMS REPLACEMENT HISTORY, Element HOPLOT_CALCOMP5800.COM
$! *1    19-JUN-1989 14:57:14 SYSTEM ""
$! DEC/CMS REPLACEMENT HISTORY, Element HOPLOT_CALCOMP5800.COM
$ASSIGN PLOT.DAT FOR009
$R NI_NEUTINT
$PRINT/QUE=TXA4 PLOT.DAT
$REPLY "PLOT STATUS AS FOLLOWS: "
$SHO QUE/FULL TXA4
